# **Beginner Numpy Notebook**

While I was learning Numpy, I decided to create a notebook for me. Here is it!

Numpy Array = Python list, but!!:


*   arrays - faster
*   lists can store mixed types (e.g. ints and floats). The data in an array must be of the same type (e.g. ints or floats but not both).

**Making 1-D Array**

In [3]:
import numpy as np

array = np.array([10,20,30,40])

**Printing Array**

In [4]:
print(array)

[10 20 30 40]


**Checking Dimensionality**

More like checking whether it is a 1D, 2D or nD array

In [5]:
print(array.ndim)

1


**Checking Shape**

In [6]:
print(array.shape)

(4,)


**Checking how many elements are there**

In [7]:
print(len(array))

4


**Making 2D array**

2D array is also formable by list of lists.

In [8]:
array_2d=np.array([[10,20,30,40],[15,25,35,45],['a','b','c','d']])
array_2d2=np.array([[10,20,30,40],[15,25,35,45]])

**Checking Dimensionality**

In [9]:
print(array_2d.ndim)
print(array_2d2.ndim)

2
2


**Checking shape**

In [10]:
print(array_2d.shape)
print(array_2d2.shape)

(3, 4)
(2, 4)


**Checking length**

In [11]:
print(len(array_2d))
print(len(array_2d2))

3
2


**Checking total element number**

In [12]:
print(array_2d.size)
print(array_2d2.size)

12
8


**Check object type**

In [13]:
print(type(array_2d))
print(type(array_2d2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**Checking the data type of elements**

In [14]:
print(array_2d.dtype)
print(array_2d2.dtype)

<U21
int64


## **Rules For Every NumPy Array¶**

There are two basic rules for every numpy array..

*   Every element in the array must be of the same type and size.
*   If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other. In other words, multidimensional arrays must be rectangular, not jagged.

Numpy won't show error if you miss this, but it will create this messier, and you won't get the advantage of using array rather than lists.


## **Numpy.zeros**

**Creating zeroes**

In [15]:
np.zeros(shape=3)

array([0., 0., 0.])

**Making Rectangular Arrays**

In [16]:
print(np.zeros(shape=(3,2)))
print(np.zeros(shape=(3,2,4)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**Filling Array with any value**

Thing to note here! np.full is used! **shape** and **fill_value** are two parameter. These parameter keyword names are hard to memorize

In [20]:
print(np.full(shape=(3,5), fill_value="cat"))
print(np.full(shape=(6,16), fill_value="Ankon Loves You!"))

[['cat' 'cat' 'cat' 'cat' 'cat']
 ['cat' 'cat' 'cat' 'cat' 'cat']
 ['cat' 'cat' 'cat' 'cat' 'cat']]
[['Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!']
 ['Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!']
 ['Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Loves You!' 'Ankon Loves You!'
  'Ankon Loves You!' 'Ankon Lo

**Making sequence array**

**np.arange** is used. It is **arange**, not arrange. There are three parameters. **start**: The starting number of the sequence. **stop**: The ending number of the sequence, **step**=distance between sequence elements.

In [22]:
np.arange(start=1, stop=16, step=1.5)
np.arange(start=1, stop=99, step=np.pi)

array([ 1.        ,  4.14159265,  7.28318531, 10.42477796, 13.56637061,
       16.70796327, 19.84955592, 22.99114858, 26.13274123, 29.27433388,
       32.41592654, 35.55751919, 38.69911184, 41.8407045 , 44.98229715,
       48.1238898 , 51.26548246, 54.40707511, 57.54866776, 60.69026042,
       63.83185307, 66.97344573, 70.11503838, 73.25663103, 76.39822369,
       79.53981634, 82.68140899, 85.82300165, 88.9645943 , 92.10618695,
       95.24777961, 98.38937226])

**Accessing *i*th element of array**

In [23]:
print(array[2])

30


**Modifying i-th element**

In [24]:
array[1]=90
print(array)

[10 90 30 40]


**Negative Indexing**

In [25]:
array[-2]

30

**Accessing multiple elements**

In [28]:
print(array[[0,1,-1,1,0]])

[10 90 40 90 10]


In [30]:
print(array[[0,2,0]])

[10 30 10]


Indices can be another numpy array!

In [31]:
print(array[np.zeros(shape=3,dtype="int64")])

[10 10 10]


**Array Slicing**

In [37]:
print(array[:2])
print(array[-2:])
print(array[::2])
print(array)
print(array[::-1])
arr=array[::-1]
print(arr)

[10 90]
[30 40]
[10 30]
[10 90 30 40]
[40 30 90 10]
[40 30 90 10]


**Modifying multiple array elements**

In [39]:
array[[0,1,2]]=[15,87,-10]
print(array)

[ 15  87 -10  40]


**2D Array**

In [40]:
array_2D=np.array([[10,20,30,40],[15,25,35,45],['-1','-2','-3','-4']])
print(array_2D)

[['10' '20' '30' '40']
 ['15' '25' '35' '45']
 ['-1' '-2' '-3' '-4']]


**Efficient value finding**

The comma seperated elements are row and column element numbers (starting from 0). Slicing can be used, too, and then, ':' is used when there is exclusivity!

In [47]:
print(array_2D[1,2])
print(array_2d[1,])
print(array_2D[1:,2])
print(array_2D[:2,:3])
print(array_2D[0:3,-2:])
print(array_2D[0,0])

35
['15' '25' '35' '45']
['35' '-3']
[['10' '20' '30']
 ['15' '25' '35']]
[['30' '40']
 ['35' '45']
 ['-3' '-4']]
10


**Inserting zeros on diagonal**

In [51]:
array_2D[[0,1,2],[0,1,2]]=[0,0,0]
print(array_2D)

[['0' '20' '30' '40']
 ['15' '0' '35' '45']
 ['-1' '-2' '0' '-4']]


**Multidimensional Array**

In [54]:
zoo = np.array([
    [
        [10,20],
        [30,40],
        [50,60],
    ],
    [
        [11,12],
        [13,14],
        [15,16],
    ]
])
print(zoo)
print("Divider-------------------------")
zoo[0,:,1] = 5
print(zoo)

[[[10 20]
  [30 40]
  [50 60]]

 [[11 12]
  [13 14]
  [15 16]]]
Divider-------------------------
[[[10  5]
  [30  5]
  [50  5]]

 [[11 12]
  [13 14]
  [15 16]]]


## **Basic Math on Arrays**

**Addition**

Adds directly the corresponding elements
Creates the missing dimension by copying

In [57]:
h1=np.array([[10,20],[30,10]])
h2=np.array([[15,25],[35,15]])
h3=np.array([[10,20]])
print(h1+h2)
print(h1+h3)

[[25 45]
 [65 25]]
[[20 40]
 [40 30]]


**Substraction**

In [58]:
print(h1-h3)
print(h1-h2)

[[  0   0]
 [ 20 -10]]
[[-5 -5]
 [-5 -5]]


**Multiplication**

This is not matrix multiplication, this is just multiplying corresponding elements.

In [59]:
print(h1*h3)
print(h1*h2)
print(h2*h3)

[[100 400]
 [300 200]]
[[ 150  500]
 [1050  150]]
[[150 500]
 [350 300]]


In [60]:
print(h1/h2)
print(h1/h3)

[[0.66666667 0.8       ]
 [0.85714286 0.66666667]]
[[1.  1. ]
 [3.  0.5]]


**Matrix Multiplication**

In [62]:
print(h1@h2)
h4=np.array([[10],[20]])
print(h1@h4)

[[850 550]
 [800 900]]
[[500]
 [500]]


**Boradcasting Arithmetic**

Here, every binary arithmetic operation takes effect on each element of the array!

In [63]:
print(h1+5-h2*3)

[[-30 -50]
 [-70 -30]]


Nice! That was it. Done. Hurray.