[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Nola](https://www.practiceprobs.com/problemsets/python-numpy/beginner/nola/)

Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

```
# nola
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
```

---

In [ ]:
import numpy as np
arr=np.full((4,7),1)
print(arr)
for i in range(4):
    if i!=0:
      arr[i,]=np.arange(arr[i-1,6]+4,arr[i-1,6]+17,2)
    elif i==0:
      arr[i,]=np.arange(arr[i][0],arr[i][0]+13,2)
print(arr)


[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


**Heavy numpy used clean solution!**

This is beautiful, and smart!

Just two lines, no manual looping!

In [ ]:
#First create a 4x8 array from 1 to 63 with step 2, and the array without the last column is our desired one!
#Use the reshape tool to arrange them in arrays of 4 rows and 8 columns
nola = np.reshape(np.arange(start=1, stop=65, step=2), (4,8))

#Select everything except the last column
nola = nola[:, :-1]

print(nola)


[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
