# [Roux](https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/)

Define a *roux* array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them.

**Examples**  

```
# roux array of length 5
[9 0 4 0 1]
```

```
# roux array of length 8
[ 0 16  0  9  0  4  0  1]
```

```
# roux array of length 12
[ 0 36  0 25  0 16  0  9  0  4  0  1]
```

**Note**: odd-length arrays begin with a square number while even-length arrays begin with a zero.

Implement a function called `make_roux(n)` that inputs `n`, the desired size of the array, and outputs the corresponding roux array. Then test it on the examples above.

---

In [1]:
import numpy as np
def make_roux(n):
    arr=np.zeros(shape=n)
    x=1
    for i in range(n):
        if (i+1)%2!=0:
            arr[i]=x**2
            x+=1
    return arr[::-1]
print(make_roux(5))
print(make_roux(8))
print(make_roux(12))


[9. 0. 4. 0. 1.]
[ 0. 16.  0.  9.  0.  4.  0.  1.]
[ 0. 36.  0. 25.  0. 16.  0.  9.  0.  4.  0.  1.]


**Numpy heavy solution!**

In [2]:
def make_roux1(n):
    """returns a roux array of length n"""

    roux = np.zeros(shape=(n,), dtype='int64')
    nsquares = np.ceil(len(roux) / 2)
    squares = (1 + np.arange(nsquares)) ** 2
    roux[::-2] = squares

    return roux

print(make_roux1(5))
print(make_roux1(8))
print(make_roux1(12))

[9 0 4 0 1]
[ 0 16  0  9  0  4  0  1]
[ 0 36  0 25  0 16  0  9  0  4  0  1]
